spring:
  datasource:
    url: jdbc:h2:mem:${H2_DB:db}
    username: ${H2_USER:sa}
    password: ${H2_PASS:password}
    driver-class-name: org.h2.Driver
  h2:
    console.enabled: true
    console.path: /h2-console
  jpa:
    defer-datasource-initialization: true #(data.sql)
    properties.hibernate:
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect

